from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN
import pandas as pd

NAVY=RGBColor(20,48,73); BLUE=RGBColor(28,100,160); PALE=RGBColor(245,248,251); LINE=RGBColor(210,218,226)
RAG={'GREEN':RGBColor(54,142,74),'AMBER':RGBColor(224,155,32),'RED':RGBColor(196,62,62)}

def _text(slide,x,y,w,h,text,size=10,bold=False,color=NAVY,align=None):
    s=slide.shapes.add_textbox(Inches(x),Inches(y),Inches(w),Inches(h)); tf=s.text_frame; tf.clear(); tf.word_wrap=True
    p=tf.paragraphs[0]; p.text=str(text); p.font.size=Pt(size); p.font.bold=bold; p.font.color.rgb=color
    if align is not None: p.alignment=align
    return s

def _box(slide,x,y,w,h,title,body=''):
    s=slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE,Inches(x),Inches(y),Inches(w),Inches(h)); s.fill.solid(); s.fill.fore_color.rgb=PALE; s.line.color.rgb=LINE
    _text(slide,x+.16,y+.10,w-.32,.28,title,11,True,BLUE)
    if body: _text(slide,x+.16,y+.44,w-.32,h-.52,body,9,False,NAVY)
    return s

def _metric(slide,x,y,w,label,value):
    s=slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE,Inches(x),Inches(y),Inches(w),Inches(.72)); s.fill.solid(); s.fill.fore_color.rgb=PALE; s.line.color.rgb=LINE
    _text(slide,x+.12,y+.08,w-.24,.22,label.upper(),7,True,BLUE); _text(slide,x+.12,y+.30,w-.24,.30,value,15,True,NAVY)

def _date(v):
    if v is None or str(v) in ('','None','NaT'): return 'N/A'
    try: return pd.to_datetime(v).strftime('%d %b %Y')
    except Exception: return str(v)

def _milestones(summary):
    raw=summary.get('milestones',[]); result=[]
    if hasattr(raw,'iterrows'):
        for _,r in raw.iterrows():
            d=r.get('finish') if r.get('finish') is not None else r.get('start'); result.append(f"• {_date(d)}   {r.get('task','')}")
    else:
        for r in raw: result.append(f"• {_date(r.get('date'))}   {r.get('task','')}")
    return result

def generate(summary,out_path):
    prs=Presentation(); prs.slide_width=Inches(13.333); prs.slide_height=Inches(7.5); slide=prs.slides.add_slide(prs.slide_layouts[6])
    _text(slide,.45,.25,10.6,.45,summary['project'],24,True,NAVY); _text(slide,.45,.73,8,.25,'PLAN ON A PAGE • EXECUTIVE VIEW',9,True,BLUE)
    rag=str(summary.get('overall_rag',summary.get('status','GREEN'))).upper(); rag=rag if rag in RAG else 'GREEN'
    badge=slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE,Inches(11.55),Inches(.28),Inches(1.3),Inches(.55)); badge.fill.solid(); badge.fill.fore_color.rgb=RAG[rag]; badge.line.fill.background(); _text(slide,11.55,.41,1.3,.22,rag,10,True,RGBColor(255,255,255),PP_ALIGN.CENTER)
    sd=_date(summary.get('start')); ed=_date(summary.get('finish')); tasks=summary.get('task_count',summary.get('tasks',0)); complete=summary.get('average_complete',summary.get('completion',0)); deps=summary.get('dependencies',0); rc=summary.get('rag_counts',{})
    _metric(slide,.45,1.15,2.0,'Tasks',str(tasks)); _metric(slide,2.58,1.15,2.0,'Average complete',f"{complete}%"); _metric(slide,4.71,1.15,2.25,'Plan start',sd); _metric(slide,7.09,1.15,2.25,'Plan finish',ed); _metric(slide,9.47,1.15,1.65,'Dependencies',str(deps)); _metric(slide,11.25,1.15,1.6,'R / A / G',f"{rc.get('RED',0)} / {rc.get('AMBER',0)} / {rc.get('GREEN',0)}")
    _box(slide,.45,2.10,3.15,2.08,'WORKSTREAMS','\n'.join('• '+x for x in summary.get('workstreams',[])))
    _box(slide,3.75,2.10,5.65,2.08,'KEY MILESTONES','\n'.join(_milestones(summary)[:8]) or 'No dated milestones detected')
    _box(slide,9.55,2.10,3.33,2.08,'STATUS','\n'.join([f"• Green: {rc.get('GREEN',0)}",f"• Amber: {rc.get('AMBER',0)}",f"• Red: {rc.get('RED',0)}",f"• Overall: {rag}"]))
    _box(slide,.45,4.36,6.15,1.48,'RISKS / ATTENTION','\n'.join('• '+x for x in summary.get('risks',[])) or '• No rule-based risks detected')
    executive=summary.get('executive_summary') or f"{tasks} activities across {len(summary.get('workstreams',[]))} detected workstream(s). Average recorded completion is {complete}%."
    _box(slide,6.75,4.36,6.13,1.48,'EXECUTIVE SUMMARY',executive)
    _box(slide,.45,6.02,12.43,.88,'TIMELINE',f"{sd}  ─────────────────────────────────────────────────────────  {ed}")
    _text(slide,.45,7.08,12.4,.18,'Generated by POAP Builder • All PowerPoint shapes and text remain editable',7,False,RGBColor(100,110,120),PP_ALIGN.RIGHT); prs.save(out_path)